// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// AccountAdder is an autogenerated mock type for the AccountAdder type
type AccountAdder struct {
	mock.Mock
}

// AddAccount provides a mock function with given fields: currency
func (_m *AccountAdder) AddAccount(currency string) (uuid.UUID, error) {
	ret := _m.Called(currency)

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uuid.UUID, error)); ok {
		return rf(currency)
	}
	if rf, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = rf(currency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAccountAdder interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccountAdder creates a new instance of AccountAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccountAdder(t mockConstructorTestingTNewAccountAdder) *AccountAdder {
	mock := &AccountAdder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
