// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// Account is an autogenerated mock type for the Account type
type Account struct {
	mock.Mock
}

// AddAccount provides a mock function with given fields: currency
func (_m *Account) AddAccount(currency string) (uuid.UUID, int64, error) {
	ret := _m.Called(currency)

	var r0 uuid.UUID
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (uuid.UUID, int64, error)); ok {
		return rf(currency)
	}
	if rf, ok := ret.Get(0).(func(string) uuid.UUID); ok {
		r0 = rf(currency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(string) int64); ok {
		r1 = rf(currency)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(currency)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewAccount interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccount creates a new instance of Account. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccount(t mockConstructorTestingTNewAccount) *Account {
	mock := &Account{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
