// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// AccountInvoicer is an autogenerated mock type for the AccountInvoicer type
type AccountInvoicer struct {
	mock.Mock
}

// Invoice provides a mock function with given fields: currency, wallet, amount
func (_m *AccountInvoicer) Invoice(currency string, wallet uuid.UUID, amount float64) error {
	ret := _m.Called(currency, wallet, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, float64) error); ok {
		r0 = rf(currency, wallet, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAccountInvoicer interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccountInvoicer creates a new instance of AccountInvoicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccountInvoicer(t mockConstructorTestingTNewAccountInvoicer) *AccountInvoicer {
	mock := &AccountInvoicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
